import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Gloria_Hallelujah, Ubuntu } from "next/font/google";
import "./globals.css";
import ClientProvider from "./client-provider"; // <-- import your client provider

const inter = Inter({ subsets: ["latin"] });
const gloria = Gloria_Hallelujah({ weight: "400", subsets: ["latin"] });
const ubuntu = Ubuntu({
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Autumn Ember",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Gloria+Hallelujah&family=Jersey+20&family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${inter.className} ${gloria.className} ${ubuntu.className}`}>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
